name: "meme_fimo"

description: Scanning a set of sequences for individual matches to each of the motifs
keywords:
  - fimo
  - meme
  - fasta
tools:
  - "meme":

      description: |
         Scanning for occurrences of a given motif
      homepage: https://meme-suite.org/meme/tools/fimo
      documentation: https://meme-suite.org/meme/doc/fimo.html
      doi: 10.1093/bioinformatics/btr064
      licence: "['https://techtransfer.universityofcalifornia.edu/NCD/20911.html']"


input:
  # Only when we have meta
  - meta:
      type: map
      description: |
        Groovy Map containing sample information
        e.g. [ id:'test', single_end:false ]
  # 

  - meme:
      type: file
      description: The name of a file containing MEME formatted motifs.
      pattern: "*.{meme}"
  - fasta:
      type: file
      description: The name of a file containing a collection of sequences in FASTA format.
      pattern: "*.{fa,fasta}"


output:
  #Only when we have meta
  - meta:
      type: map
      description: |
        Groovy Map containing sample information
        e.g. [ id:'test', single_end:false ]
  # 
  - versions:
      type: file
      description: File containing software versions
      pattern: "versions.yml"

  - html:
      type: file
      description: an HTML file that provides the results in a human-readable format
      pattern: "*.{html}"
  - tsv:
      type: file
      description: a TSV (tab-separated values) file that provides the results in a format suitable for parsing by scripts and viewing with Excel
      pattern: "*.{tsv}"
  - gff:
      type: file
      description:  a GFF3 format file that provides the results in a format suitable for display in the UCSC genome browser
      pattern: "*.{gff}"
  - cismlxml:
      type: file
      description:  that provides the results in the CisML schema
      pattern: "*.{_cisml.xml}"
  - fimoxml:
      type: file
      description:  that describes the inputs to FIMO and references the CISML file cisml.xml
      pattern: "*.{_fimo.xml}"

authors:
  - "@n-yamauchi"
