name: "meme_mast"
## TODO nf-core: Add a description of the module and list keywords
description: Searches sequences for matches to a set of motifs, and sorts the sequences by the best combined match to all motifs
keywords:
  - mast
  - meme
  - fasta
tools:
  - "meme":
      ## TODO nf-core: Add a description and other details for the software below
      description: "Scanning for occurrences of a given motif"
      homepage: https://meme-suite.org/meme/tools/mast
      documentation: https://meme-suite.org/meme/doc/mast.html
      doi: 10.1093/bioinformatics/14.1.48
      licence: "['https://techtransfer.universityofcalifornia.edu/NCD/20911.html']"

## TODO nf-core: Add a description of all of the variables used as input
input:
  # Only when we have meta
  - meta:
      type: map
      description: |
        Groovy Map containing sample information
        e.g. [ id:'test', single_end:false ]
  # 
  ## TODO nf-core: Delete / customise this example input
  - meme:
      type: file
      description: The name of a file containing MEME formatted motifs.
      pattern: "*.{meme}"
  - fasta:
      type: file
      description: The name of a file containing a collection of sequences in FASTA format.
      pattern: "*.{fa,fasta}"

## TODO nf-core: Add a description of all of the variables used as output
output:
  #Only when we have meta
  - meta:
      type: map
      description: |
        Groovy Map containing sample information
        e.g. [ id:'test', single_end:false ]
  # 
  - versions:
      type: file
      description: File containing software versions
      pattern: "versions.yml"
  ## TODO nf-core: Delete / customise this example output
  - html:
      type: file
      description: an HTML file that provides the results in a human-readable format
      pattern: "*.{html}"
  - txt:
      type: file
      description: a plain text file of the results for backwards compatibility with earlier versions of MAST
      pattern: "*.{txt}"
  - xml:
      type: file
      description: an XML file that provides the results in a format designed for machine processing
      pattern: "*.{xml}"

authors:
  - "@n-yamauchi"
